/**
 * Icon exports for dashboard components
 * Uses lucide-react for consistent iconography
 */

import {
  Flame,
  Zap,
  Target,
  Trophy,
  Clock,
  TrendingUp,
  BookOpen,
  Brain,
  Calendar,
  CheckCircle2,
  Circle,
  Award,
  Star,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Play,
  Pause,
  RefreshCw,
  Settings,
  HelpCircle,
  MessageCircle,
  Bell,
  Search,
  Menu,
  X,
  Plus,
  Minus,
  Edit,
  Trash2,
  Download,
  Upload,
  Share2,
  Copy,
  ExternalLink,
  ArrowRight,
  ArrowLeft,
  Info,
  AlertCircle,
  AlertTriangle,
  Volume2,
  VolumeX,
  Sun,
  Moon,
  Sparkles,
  Heart,
  Bookmark,
  Flag,
  BarChart2,
  PieChart,
  Activity,
  TrendingDown,
  Users,
  User,
  Mail,
  Lock,
  Eye,
  EyeOff,
  Home,
  FileText,
  Folder,
  Image,
  Video,
  Headphones,
  Mic,
  Camera,
  MapPin,
  Compass,
  Globe,
  Wifi,
  WifiOff,
  Battery,
  BatteryCharging,
  Bluetooth,
  Smartphone,
  Tablet,
  Laptop,
  Monitor,
  Printer,
  Server,
  Database,
  Cloud,
  CloudOff,
  CloudUpload,
  CloudDownload,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Github,
  Code,
  Terminal,
  Package,
  Box,
  Archive,
  Inbox,
  Send,
  Paperclip,
  Link,
  Unlink,
  Scissors,
  Clipboard,
  Save,
  Loader2,
  MoreHorizontal,
  MoreVertical,
} from 'lucide-react'

// Custom icon components
export const Icons = {
  flame: Flame,
  lightning: Zap,
  target: Target,
  trophy: Trophy,
  clock: Clock,
  trendingUp: TrendingUp,
  book: BookOpen,
  brain: Brain,
  calendar: Calendar,
  checkCircle: CheckCircle2,
  circle: Circle,
  award: Award,
  star: Star,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  play: Play,
  pause: Pause,
  refresh: RefreshCw,
  settings: Settings,
  help: HelpCircle,
  message: MessageCircle,
  bell: Bell,
  search: Search,
  menu: Menu,
  close: X,
  plus: Plus,
  minus: Minus,
  edit: Edit,
  trash: Trash2,
  download: Download,
  upload: Upload,
  share: Share2,
  copy: Copy,
  externalLink: ExternalLink,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  info: Info,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  volume: Volume2,
  volumeOff: VolumeX,
  sun: Sun,
  moon: Moon,
  sparkles: Sparkles,
  heart: Heart,
  bookmark: Bookmark,
  flag: Flag,
  barChart: BarChart2,
  pieChart: PieChart,
  activity: Activity,
  trendingDown: TrendingDown,
  users: Users,
  user: User,
  mail: Mail,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  home: Home,
  fileText: FileText,
  folder: Folder,
  image: Image,
  video: Video,
  headphones: Headphones,
  mic: Mic,
  camera: Camera,
  mapPin: MapPin,
  compass: Compass,
  globe: Globe,
  wifi: Wifi,
  wifiOff: WifiOff,
  battery: Battery,
  batteryCharging: BatteryCharging,
  bluetooth: Bluetooth,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  monitor: Monitor,
  printer: Printer,
  server: Server,
  database: Database,
  cloud: Cloud,
  cloudOff: CloudOff,
  cloudUpload: CloudUpload,
  cloudDownload: CloudDownload,
  gitBranch: GitBranch,
  gitCommit: GitCommit,
  gitMerge: GitMerge,
  gitPullRequest: GitPullRequest,
  gitHub: Github,
  code: Code,
  terminal: Terminal,
  package: Package,
  box: Box,
  archive: Archive,
  inbox: Inbox,
  send: Send,
  paperclip: Paperclip,
  link: Link,
  unlink: Unlink,
  scissors: Scissors,
  clipboard: Clipboard,
  save: Save,
  spinner: Loader2,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
} as const
