/**
 * AUTO-GENERATED PLACEHOLDER
 * The real file is generated by apps/api/scripts/generate_types.py.
 * This stub keeps imports type-safe until CI generation runs.
 */
export type __ApiTypesPlaceholder = Record<string, never>
